/* Common SQL DDL, DML, and DCL statements 
DEPRECATED: Use location2.sql instead
*/

-- CREATE TABLE

CREATE TABLE dim_location(
    id   INT PRIMARY KEY AUTO_INCREMENT,
    country           VARCHAR(100) NOT NULL,
    state         VARCHAR(100),
    municipality         VARCHAR(100),
    name VARCHAR(255)
);

-- INSERT INTO

-- Chilean locations, without accent marks
INSERT INTO dim_location (country, state, municipality, name)
VALUES
('Chile', 'Region Metropolitana', 'Santiago', 'Santiago'),
('Chile', 'Region Metropolitana', 'Providencia', 'Providencia'),
('Chile', 'Region Metropolitana', 'Las Condes', 'Las Condes'),
('Chile', 'Region Metropolitana', 'Puente Alto', 'Puente Alto'),
('Chile', 'Region Metropolitana', 'Maipú', 'Maipú'),
('Chile', 'Region Metropolitana', 'La Florida', 'La Florida'),
('Chile', 'Region Metropolitana', 'San Bernardo', 'San Bernardo'),
('Chile', 'Region Metropolitana', 'Ñuñoa', 'Ñuñoa'),
('Chile', 'Region Metropolitana', 'La Reina', 'La Reina'),
('Chile', 'Region Metropolitana', 'Melipilla', 'Melipilla'),
('Chile', 'Region Metropolitana', 'Colina', 'Colina'),
('Chile', 'Region Metropolitana', 'Puente Alto', 'Puente Alto'),
('Chile', 'Region Metropolitana', 'San Miguel', 'San Miguel'),
('Chile', 'Region Metropolitana', 'Independencia', 'Independencia'),
('Chile', 'Region Metropolitana', 'Recoleta', 'Recoleta'),
('Chile', 'Region Metropolitana', 'Huechuraba', 'Huechuraba'),
('Chile', 'Region Metropolitana', 'Lo Barnechea', 'Lo Barnechea'),
('Chile', 'Region Metropolitana', 'Cerrillos', 'Cerrillos'),
('Chile', 'Region Metropolitana', 'El Bosque', 'El Bosque'),
('Chile', 'Region Metropolitana', 'La Cisterna', 'La Cisterna'),
('Chile', 'Region Metropolitana', 'Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'),
('Chile', 'Region Metropolitana', 'San Joaquín', 'San Joaquín'),
('Chile', 'Region Metropolitana', 'San Ramon', 'San Ramon'),
('Chile', 'Region Metropolitana', 'La Granja', 'La Granja'),
('Chile', 'Region Metropolitana', 'San Ramon', 'San Ramon'),
('Chile', 'Region Metropolitana', 'La Pintana', 'La Pintana'),
('Chile', 'Region Metropolitana', 'El Monte', 'El Monte'),
('Chile', 'Region Metropolitana', 'Talagante', 'Talagante'),
('Chile', 'Region Metropolitana', 'Isla de Maipo', 'Isla de Maipo'),
('Chile', 'Region Metropolitana', 'Padre Hurtado', 'Padre Hurtado'),
('Chile', 'Region Metropolitana', 'Peñaflor', 'Peñaflor'),
('Chile', 'Region Metropolitana', 'San Pedro', 'San Pedro'),
('Chile', 'Region Metropolitana', 'Melipilla', 'Melipilla'),
('Chile', 'Region Metropolitana', 'Curacaví', 'Curacaví'),
('Chile', 'Region Metropolitana', 'María Pinto', 'María Pinto'),
('Chile', 'Region Metropolitana', 'Alhué', 'Alhué'),
('Chile', 'Region Metropolitana', 'San José de Maipo', 'San José de Maipo'),
('Chile', 'Region Metropolitana', 'Pirque', 'Pirque'),
('Chile', 'Region Metropolitana', 'Buin', 'Buin'),
('Chile', 'Region Metropolitana', 'Calera de Tango', 'Calera de Tango'),
('Chile', 'Region Metropolitana', 'Lampa', 'Lampa'),
('Chile', 'Region Metropolitana', 'Tiltil', 'Tiltil'),
('Chile', 'Region Metropolitana', 'Colina', 'Colina'),
('Chile', 'Region Metropolitana', 'Cerro Navia', 'Cerro Navia'),


('Chile', 'Region de Valparaíso', 'Quilpué', 'Quilpué'),
('Chile', 'Region de Valparaíso', 'Villa Alemana', 'Villa Alemana'),
('Chile', 'Region de Valparaíso', 'Valparaíso', 'Valparaíso'),
('Chile', 'Region de Valparaíso', 'Viña del Mar', 'Viña del Mar'),
('Chile', 'Region de Valparaíso', 'Quillota', 'Quillota'),
('Chile', 'Region de Valparaíso', 'San Antonio', 'San Antonio'),
('Chile', 'Region de Valparaíso', 'Los Andes', 'Los Andes'),
('Chile', 'Region de Valparaíso', 'La Ligua', 'La Ligua'),
('Chile', 'Region de Valparaíso', 'San Felipe', 'San Felipe'),
('Chile', 'Region de Valparaíso', 'Limache', 'Limache'),
('Chile', 'Region de Valparaíso', 'Olmué', 'Olmué'),
('Chile', 'Region de Valparaíso', 'Casablanca', 'Casablanca'),
('Chile', 'Region de Valparaíso', 'Concón', 'Concón'),
('Chile', 'Region de Valparaíso', 'Puchuncaví', 'Puchuncaví'),
('Chile', 'Region de Valparaíso', 'Catemu', 'Catemu'),
('Chile', 'Region de Valparaíso', 'Panquehue', 'Panquehue'),
('Chile', 'Region de Valparaíso', 'Hijuelas', 'Hijuelas'),
('Chile', 'Region de Valparaíso', 'Nogales', 'Nogales'),
('Chile', 'Region de Valparaíso', 'Algarrobo', 'Algarrobo'),
('Chile', 'Region de Valparaíso', 'El Quisco', 'El Quisco'),
('Chile', 'Region de Valparaíso', 'El Tabo', 'El Tabo'),
('Chile', 'Region de Valparaíso', 'Cartagena', 'Cartagena'),
('Chile', 'Region de Valparaíso', 'Santo Domingo', 'Santo Domingo'),
('Chile', 'Region de Valparaíso', 'Calle Larga', 'Calle Larga'),
('Chile', 'Region de Valparaíso', 'Rinconada', 'Rinconada'),
('Chile', 'Region de Valparaíso', 'San Esteban', 'San Esteban'),
('Chile', 'Region de Valparaíso', 'La Calera', 'La Calera'),

('Chile', 'Region del Biobío', 'Concepcion', 'Concepcion'),
('Chile', 'Region del Biobío', 'Chillán', 'Chillán'),
('Chile', 'Region del Biobío', 'Los Ángeles', 'Los Ángeles'),
('Chile', 'Region del Biobío', 'Talcahuano', 'Talcahuano'),
('Chile', 'Region del Biobío', 'Coronel', 'Coronel'),
('Chile', 'Region del Biobío', 'Hualpén', 'Hualpén'),
('Chile', 'Region del Biobío', 'San Pedro de la Paz', 'San Pedro de la Paz'),
('Chile', 'Region del Biobío', 'Lota', 'Lota'),
('Chile', 'Region del Biobío', 'Penco', 'Penco'),
('Chile', 'Region del Biobío', 'Tomé', 'Tomé'),
('Chile', 'Region del Biobío', 'Arauco', 'Arauco'),
('Chile', 'Region del Biobío', 'Curanilahue', 'Curanilahue'),

('Chile', 'Region de La Araucanía', 'Temuco', 'Temuco'),
('Chile', 'Region de La Araucanía', 'Villarrica', 'Villarrica'),
('Chile', 'Region de La Araucanía', 'Angol', 'Angol'),
('Chile', 'Region de La Araucanía', 'Pucón', 'Pucón'),
('Chile', 'Region de La Araucanía', 'Loncoche', 'Loncoche'),
('Chile', 'Region de La Araucanía', 'Carahue', 'Carahue'),
('Chile', 'Region de La Araucanía', 'Nueva Imperial', 'Nueva Imperial'),
('Chile', 'Region de La Araucanía', 'Melipeuco', 'Melipeuco'),
('Chile', 'Region de La Araucanía', 'Freire', 'Freire'),
('Chile', 'Region de La Araucanía', 'Collipulli', 'Collipulli'),
('Chile', 'Region de La Araucanía', 'Toltén', 'Toltén'),
('Chile', 'Region de La Araucanía', 'Gorbea', 'Gorbea'),
('Chile', 'Region de La Araucanía', 'Lautaro', 'Lautaro'),
('Chile', 'Region de La Araucanía', 'Vilcún', 'Vilcún'),
('Chile', 'Region de La Araucanía', 'Cunco', 'Cunco'),
('Chile', 'Region de La Araucanía', 'Pitrufquén', 'Pitrufquén'),
('Chile', 'Region de La Araucanía', 'Curarrehue', 'Curarrehue'),
('Chile', 'Region de La Araucanía', 'Perquenco', 'Perquenco'),
('Chile', 'Region de La Araucanía', 'Cholchol', 'Cholchol'),
('Chile', 'Region de La Araucanía', 'Padre Las Casas', 'Padre Las Casas'),

('Chile', 'Region de Los Lagos', 'Puerto Montt', 'Puerto Montt'),
('Chile', 'Region de Los Lagos', 'Osorno', 'Osorno')
('Chile', 'Region de Los Lagos', 'Ancud', 'Ancud'),
('Chile', 'Region de Los Lagos', 'Castro', 'Castro'),
('Chile', 'Region de Los Lagos', 'Quellón', 'Quellón'),
('Chile', 'Region de Los Lagos', 'Puerto Varas', 'Puerto Varas'),
('Chile', 'Region de Los Lagos', 'Purranque', 'Purranque'),
('Chile', 'Region de Los Lagos', 'Calbuco', 'Calbuco'),
('Chile', 'Region de Los Lagos', 'Llanquihue', 'Llanquihue'),
('Chile', 'Region de Los Lagos', 'Frutillar', 'Frutillar'),
('Chile', 'Region de Los Lagos', 'Cochamó', 'Cochamó'),

('Chile', 'Region de Antofagasta', 'Antofagasta', 'Antofagasta'),
('Chile', 'Region de Antofagasta', 'Calama', 'Calama'),
('Chile', 'Region de Antofagasta', 'Tocopilla', 'Tocopilla'),
('Chile', 'Region de Antofagasta', 'Mejillones', 'Mejillones'),
('Chile', 'Region de Antofagasta', 'San Pedro de Atacama', 'San Pedro de Atacama'),

('Chile', 'Region de Coquimbo', 'Illapel', 'Illapel'),
('Chile', 'Region de Coquimbo', 'La Serena', 'La Serena'),
('Chile', 'Region de Coquimbo', 'Coquimbo', 'Coquimbo'),
('Chile', 'Region de Coquimbo', 'Ovalle', 'Ovalle'),
('Chile', 'Region de Coquimbo', 'Combarbalá', 'Combarbalá'),
('Chile', 'Region de Coquimbo', 'Andacollo', 'Andacollo'),
('Chile', 'Region de Coquimbo', 'Los Vilos', 'Los Vilos'),
('Chile', 'Region de Coquimbo', 'Salamanca', 'Salamanca'),
('Chile', 'Region de Coquimbo', 'Vicuña', 'Vicuña'),

('Chile', 'Region de Atacama', 'Copiapo', 'Copiapo'),
('Chile', 'Region de Atacama', 'Vallenar', 'Vallenar'),
('Chile', 'Region de Atacama', 'Diego de Almagro', 'Diego de Almagro'),
('Chile', 'Region de Atacama', 'Chañaral', 'Chañaral'),
('Chile', 'Region de Atacama', 'Caldera', 'Caldera'),
('Chile', 'Region de Atacama', 'Tierra Amarilla', 'Tierra Amarilla'),

('Chile', 'Region de Tarapacá', 'Iquique', 'Iquique'),
('Chile', 'Region de Tarapacá', 'Alto Hospicio', 'Alto Hospicio'),
('Chile', 'Region de Tarapacá', 'Pozo Almonte', 'Pozo Almonte'),
('Chile', 'Region de Tarapacá', 'Pica', 'Pica'),
('Chile', 'Region de Tarapacá', 'Camiña', 'Camiña'),
('Chile', 'Region de Tarapacá', 'Colchane', 'Colchane'),
('Chile', 'Region de Tarapacá', 'Huara', 'Huara'),

('Chile', 'Region de Arica y Parinacota', 'Camarones', 'Camarones'),
('Chile', 'Region de Arica y Parinacota', 'Arica', 'Arica'),
('Chile', 'Region de Arica y Parinacota', 'Putre', 'Putre'),
('Chile', 'Region de Arica y Parinacota', 'General Lagos', 'General Lagos'),

('Chile', 'Region de Ñuble', 'Chillán Viejo', 'Chillán Viejo'),
('Chile', 'Region de Ñuble', 'Bulnes', 'Bulnes'),
('Chile', 'Region de Ñuble', 'Chillán Viejo', 'Chillán Viejo'),
('Chile', 'Region de Ñuble', 'Bulnes', 'Bulnes'),
('Chile', 'Region de Ñuble', 'San Carlos', 'San Carlos'),
('Chile', 'Region de Ñuble', 'Quillón', 'Quillón'),
('Chile', 'Region de Ñuble', 'Pemuco', 'Pemuco'),
('Chile', 'Region de Ñuble', 'Yungay', 'Yungay'),
('Chile', 'Region de Ñuble', 'Coelemu', 'Coelemu'),
('Chile', 'Region de Ñuble', 'Ninhue', 'Ninhue'),
('Chile', 'Region de Ñuble', 'Treguaco', 'Treguaco'),
('Chile', 'Region de Ñuble', 'Ránquil', 'Ránquil'),
('Chile', 'Region de Ñuble', 'El Carmen', 'El Carmen'),
('Chile', 'Region de Ñuble', 'Pinto', 'Pinto'),
('Chile', 'Region de Ñuble', 'San Ignacio', 'San Ignacio'),
('Chile', 'Region de Ñuble', 'San Fabián', 'San Fabián'),
('Chile', 'Region de Ñuble', 'Cobquecura', 'Cobquecura'),
('Chile', 'Region de Ñuble', 'Quirihue', 'Quirihue'),

('Chile', 'Region del Maule', 'Talca', 'Talca'),
('Chile', 'Region del Maule', 'Curico', 'Curico'),
('Chile', 'Region del Maule', 'Linares', 'Linares'),
('Chile', 'Region del Maule', 'Maule', 'Maule'),
('Chile', 'Region del Maule', 'San Javier', 'San Javier'),
('Chile', 'Region del Maule', 'Constitucion', 'Constitucion'),
('Chile', 'Region del Maule', 'Cauquenes', 'Cauquenes'),
('Chile', 'Region del Maule', 'Villa Alegre', 'Villa Alegre'),
('Chile', 'Region del Maule', 'Longavi', 'Longavi'),
('Chile', 'Region del Maule', 'Retiro', 'Retiro'),
('Chile', 'Region del Maule', 'Colbún', 'Colbún'),
('Chile', 'Region del Maule', 'Rauco', 'Rauco'),
('Chile', 'Region del Maule', 'Romeral', 'Romeral'),
('Chile', 'Region del Maule', 'Sagrada Familia', 'Sagrada Familia'),
('Chile', 'Region del Maule', 'Pelarco', 'Pelarco'),
('Chile', 'Region del Maule', 'San Clemente', 'San Clemente'),
('Chile', 'Region del Maule', 'Molina', 'Molina'),
('Chile', 'Region del Maule', 'Río Claro', 'Río Claro'),
('Chile', 'Region del Maule', 'Empedrado', 'Empedrado'),

('Chile', 'Region del Libertador General Bernardo OHiggins', 'Rancagua', 'Rancagua'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'San Fernando', 'San Fernando'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Pichilemu',  'Pichilemu'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Santa Cruz', 'Santa Cruz'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Machalí', 'Machalí'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Graneros', 'Graneros'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Mostazal', 'Mostazal'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Codegua', 'Codegua'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Coltauco', 'Coltauco'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Doñihue', 'Doñihue'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Requínoa', 'Requínoa'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Las Cabras', 'Las Cabras'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Peumo', 'Peumo'),
('Chile', 'Region del Libertador General Bernardo OHiggins', 'Paredones', 'Paredones'),

('Chile', 'Region de Los Ríos', 'Río Bueno', 'Río Bueno'),
('Chile', 'Region de Los Ríos', 'Lago Ranco', 'Lago Ranco'),
('Chile', 'Region de Los Ríos', 'Futrono', 'Futrono'),
('Chile', 'Region de Los Ríos', 'La Unión', 'La Unión'),
('Chile', 'Region de Los Ríos', 'Paillaco', 'Paillaco'),
('Chile', 'Region de Los Ríos', 'Panguipulli', 'Panguipulli'),
('Chile', 'Region de Los Ríos', 'Valdivia', 'Valdivia'),
('Chile', 'Region de Los Ríos', 'La Union', 'La Union'),

('Chile', 'Region de Magallanes y de la Antártica Chilena', 'Punta Arenas', 'Punta Arenas'),
('Chile', 'Region de Magallanes y de la Antártica Chilena', 'Puerto Natales', 'Puerto Natales'),
('Chile', 'Region de Magallanes y de la Antártica Chilena', 'Porvenir', 'Porvenir'),
('Chile', 'Region de Magallanes y de la Antártica Chilena', 'Cabo de Hornos', 'Cabo de Hornos'),
('Chile', 'Region de Magallanes y de la Antártica Chilena', 'Laguna Blanca', 'Laguna Blanca'),
('Chile', 'Region de Magallanes y de la Antártica Chilena', 'San Gregorio', 'San Gregorio'),

('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Aysén', 'Aysén'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Coyhaique', 'Coyhaique'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Puerto Aysén', 'Puerto Aysén'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Chile Chico', 'Chile Chico'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Cisnes', 'Cisnes'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Guaitecas', 'Guaitecas'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Lago Verde', 'Lago Verde'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Río Ibáñez', 'Río Ibáñez'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Tortel', 'Tortel'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'OHiggins', 'OHiggins'),
('Chile', 'Region de Aysén del General Carlos Ibáñez del Campo', 'Cochrane', 'Cochrane');



